# Default values for lemans-resources.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: lemans-resources
image:
  repository: jpalash/borathon-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
  name: lemans-resources
app: lemans-resources-service
resources:
 limits:
   cpu: 100m
   memory: 1Gi
 requests:
   cpu: 100m
   memory: 1Gi

