# Default values for lint-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: lint-app
image:
  repository: jpalash/borathon-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
  name: lint-app

resources:
 limits:
   cpu: 500m
   memory: 1Gi
 requests:
   cpu: 300m
   memory: 1Gi
