# Default values for bifrost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: jpalash/bifrost
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  name: bifrost
  

resources:
 limits:
   cpu: 200m
   memory: 1Gi
 requests:
   cpu: 200m
   memory: 1Gi