# Default values for lemans-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: lemans-gateway
image:
  repository: jpalash/borathon-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
  name: lemans-gateway
app: lemans-gateway-service
resources:
 limits:
   cpu: 500m
   memory: 2Gi
 requests:
   cpu: 400m
   memory: 2Gi
