apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: borathon-app
    component: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: borathon-app
        component: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
            - name: Token
              value: "{{ .Values.token }}"
      imagePullSecrets:
      - name: build-artifactory-creds