apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.name }}
    component: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: "borathon-app"
  selector:
    matchLabels:
      app: {{ .Values.name }}
      component: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        component: {{ .Release.Name }}
    spec:
      nodeSelector:
        dedicated-two: node-2
      tolerations:
      - key: dedicated-two
        operator: Equal
        value: node-2
        effect: NoSchedule
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        ports:
        - containerPort: 8080