# Default values for cost-analysis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rreplicaCount: 1
name: cost-analysis
image:
  repository: jpalash/borathon-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
  name: cost-analysis

resources:
 limits:
   cpu: 500m
   memory: 2Gi
 requests:
   cpu: 300m
   memory: 1Gi