# Default values for cortex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: cortex
image:
  repository: jpalash/borathon-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
  name: cortex

resources:
 limits:
   cpu: 200m
   memory: 1Gi
 requests:
   cpu: 200m
   memory: 1Gi
