# Default values for stargate-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: stargate-deployment
image:
  repository: jpalash/borathon-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080
  name: stargate-deployment
app: stargate-deployment-service
resources:
 limits:
   cpu: 800m
   memory: 1Gi
 requests:
   cpu: 500m
   memory: 1Gi