apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: bifrost
    component: {{ .Release.Name }}
spec:
  ports:
  - port: 8080
  type: {{ .Values.service.type }}
  selector:
    app: bifrost
    component: {{ .Release.Name }}