apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
    component: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http-port
    targetPort: 8080
  selector:
    app: {{ .Values.service.name }}
    component: {{ .Release.Name }}